name: General_Use
channels:
  - defaults
dependencies:
  - anaconda_prompt=1.1.0=haa95532_1
  - anyio=4.10.0=py313haa95532_0
  - argon2-cffi=25.1.0=py313haa95532_0
  - argon2-cffi-bindings=25.1.0=py313h02ab6af_0
  - asttokens=3.0.0=py313haa95532_0
  - async-lru=2.0.5=py313haa95532_0
  - attrs=25.4.0=py313haa95532_2
  - babel=2.17.0=py313haa95532_0
  - beautifulsoup4=4.14.2=py313haa95532_0
  - bleach=6.3.0=py313haa95532_0
  - brotlicffi=1.2.0.0=py313h885b0b7_0
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - certifi=2026.01.04=py313haa95532_0
  - cffi=2.0.0=py313h02ab6af_1
  - charset-normalizer=3.4.4=py313haa95532_0
  - colorama=0.4.6=py313haa95532_0
  - comm=0.2.3=py313haa95532_0
  - debugpy=1.8.16=py313h885b0b7_1
  - decorator=5.2.1=py313haa95532_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - executing=2.2.1=py313haa95532_0
  - expat=2.7.3=h885b0b7_4
  - h11=0.16.0=py313haa95532_1
  - html5lib=1.1=pyhd3eb1b0_0
  - httpcore=1.0.9=py313haa95532_0
  - httpx=0.28.1=py313haa95532_1
  - idna=3.11=py313haa95532_0
  - ipykernel=6.31.0=py313h4442805_0
  - ipython=9.7.0=py313haa95532_0
  - ipython_pygments_lexers=1.1.1=py313haa95532_0
  - jedi=0.19.2=py313haa95532_0
  - jinja2=3.1.6=py313haa95532_0
  - json5=0.12.1=py313haa95532_0
  - jsonschema=4.25.1=py313haa95532_0
  - jsonschema-specifications=2025.9.1=py313haa95532_0
  - jupyter-lsp=2.2.5=py313haa95532_0
  - jupyter_client=8.8.0=py313haa95532_0
  - jupyter_core=5.9.1=py313haa95532_0
  - jupyter_events=0.12.0=py313haa95532_1
  - jupyter_server=2.17.0=py313haa95532_0
  - jupyter_server_terminals=0.5.3=py313haa95532_0
  - jupyterlab_pygments=0.3.0=py313haa95532_0
  - jupyterlab_server=2.28.0=py313haa95532_0
  - libexpat=2.7.3=h885b0b7_4
  - libffi=3.4.4=hd77b12b_1
  - libmpdec=4.0.0=h827c3e9_0
  - libsodium=1.0.20=h83e8143_0
  - markupsafe=3.0.2=py313h827c3e9_0
  - matplotlib-inline=0.2.1=py313haa95532_0
  - mistune=3.1.2=py313haa95532_0
  - nbclient=0.10.2=py313haa95532_0
  - nbconvert-core=7.16.6=py313haa95532_0
  - nbformat=5.10.4=py313haa95532_0
  - nest-asyncio=1.6.0=py313haa95532_0
  - notebook-shim=0.2.4=py313haa95532_0
  - openssl=3.0.18=h543e019_0
  - packaging=25.0=py313haa95532_1
  - pandocfilters=1.5.1=py313haa95532_0
  - parso=0.8.5=py313haa95532_0
  - pip=25.3=pyhc872135_0
  - platformdirs=4.5.0=py313haa95532_0
  - prometheus_client=0.21.1=py313haa95532_0
  - prompt-toolkit=3.0.52=py313haa95532_1
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - psutil=7.0.0=py313h02ab6af_1
  - pure_eval=0.2.3=py313haa95532_0
  - pycparser=2.23=py313haa95532_0
  - pygments=2.19.2=py313haa95532_0
  - python=3.13.5=h286a616_100_cp313
  - python-dateutil=2.9.0post0=py313haa95532_2
  - python-fastjsonschema=2.21.2=py313haa95532_0
  - python-json-logger=4.0.0=py313haa95532_0
  - python_abi=3.13=3_cp313
  - pywin32=311=py313h885b0b7_0
  - pywinpty=2.0.15=py313h72d21ff_0
  - pyyaml=6.0.3=py313hb9a58be_0
  - pyzmq=27.1.0=py313h7149c55_1
  - referencing=0.37.0=py313haa95532_0
  - requests=2.32.5=py313haa95532_1
  - rfc3339-validator=0.1.4=py313haa95532_0
  - rfc3986-validator=0.1.1=py313haa95532_0
  - rpds-py=0.28.0=py313h114bc41_0
  - send2trash=1.8.3=py313haa95532_0
  - setuptools=80.9.0=py313haa95532_0
  - six=1.17.0=py313haa95532_0
  - sniffio=1.3.1=py313haa95532_0
  - soupsieve=2.5=py313haa95532_0
  - sqlite=3.51.1=hda9a48d_0
  - stack_data=0.6.3=py313haa95532_0
  - terminado=0.18.1=py313haa95532_0
  - tinycss2=1.4.0=py313haa95532_0
  - tk=8.6.15=hf199647_0
  - tornado=6.5.4=py313h02ab6af_0
  - traitlets=5.14.3=py313haa95532_0
  - typing-extensions=4.15.0=py313haa95532_0
  - typing_extensions=4.15.0=py313haa95532_0
  - ucrt=10.0.22621.0=haa95532_0
  - urllib3=2.6.3=py313haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wcwidth=0.2.14=py313haa95532_0
  - webencodings=0.5.1=py313haa95532_2
  - websocket-client=1.8.0=py313haa95532_0
  - wheel=0.45.1=py313haa95532_0
  - win_inet_pton=1.1.0=py313haa95532_1
  - winpty=0.4.3=4
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - zeromq=4.3.5=h6c54ac7_1
  - zlib=1.2.13=h500123d_2
  - pip:
      - ansitable==0.11.4
      - arrow==1.4.0
      - cfgv==3.4.0
      - clarabel==0.11.1
      - colored==2.3.1
      - contourpy==1.3.3
      - cvxpy==1.7.2
      - cycler==0.12.1
      - distlib==0.4.0
      - filelock==3.20.0
      - fonttools==4.59.2
      - fqdn==1.5.1
      - identify==2.6.15
      - isoduration==20.11.0
      - joblib==1.5.2
      - jsonpointer==3.0.0
      - jupyterlab==4.5.3
      - kiwisolver==1.4.9
      - lark==1.3.1
      - matplotlib==3.10.6
      - mpmath==1.3.0
      - nodeenv==1.9.1
      - notebook==7.5.2
      - numpy==2.4.1
      - osqp==1.0.4
      - pandas==3.0.0
      - pgraph-python==0.6.3
      - pillow==11.3.0
      - pre-commit==4.3.0
      - progress==1.6.1
      - pybullet==3.2.7
      - pyparsing==3.2.3
      - pysocks==1.7.1
      - rfc3987-syntax==1.1.0
      - roboticstoolbox-python==1.1.1
      - rtb-data==1.0.1
      - scikit-learn==1.8.0
      - scipy==1.16.2
      - scs==3.2.8
      - spatialgeometry==1.1.0
      - spatialmath-python==1.1.14
      - swift-sim==1.1.0
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - tzdata==2025.3
      - uri-template==1.3.0
      - virtualenv==20.35.4
      - webcolors==25.10.0
      - websockets==15.0.1
prefix: C:\Users\slipf\anaconda3\envs\General_Use
